apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: devtools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.22.1
          ports:
            - containerPort: 3000
            - containerPort: 22
          env:
            - name: GITEA__server__ROOT_URL
              value: http://192.168.1.50/gitea/
            - name: GITEA__server__DOMAIN
              value: 192.168.1.50
            - name: GITEA__server__SSH_DOMAIN
              value: 192.168.1.50
            - name: GITEA__server__START_SSH_SERVER
              value: "false"
            - name: GITEA__server__OFFLINE_MODE
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: gitea-data
