apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          env:
          - name: WEBSOCKET_ENABLED
            value: "true"
          - name: SIGNUPS_ALLOWED
            value: "true"
          - name: ROCKET_ADDRESS
            value: "0.0.0.0"
          - name: DOMAIN
            value: "http://192.168.1.50:30080"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: apps
spec:
  type: NodePort
  selector:
    app: vaultwarden
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080