apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-whoami
  namespace: apps
spec:
  stripPrefix:
    prefixes:
      - /whoami
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-kuma
  namespace: observability
spec:
  stripPrefix:
    prefixes:
      - /kuma
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-files
  namespace: devtools
spec:
  stripPrefix:
    prefixes:
      - /files
